### ISSUE TITLE
Is ICE really needed with AWS cost explorer there

### ISSUE THREAD

**Issue by moha297** [Teevity/ice#235]
I have been playing around with ICE and AWS cloud explorer. Deciding what value adds are existing in ICE vs Cloud reports - I would like to ask the community what are the pros and cons in their opinion about using ICE.

**Comment by nfonrose** [comment]
**Short answer** : Yes, there are many reasons to use ICE if you go above basic cost analytics


**Long(er) answer** : Even if AWS cloud explorer improves regularly (and is probably enough for many basic cost management use cases), ICE is still way ahead.

It was created years ago, but at the time Netflix already had a ton of experience dealing with Cloud spending and it had embedded inside ICE a lot of know-how in terms of cost management and cost optimization.

**Here are a few things where ICE is ahead of Cost Reports** (as of Jan 17)
- _Cost breakdown by multiple tags_ (eg: Application / Component / Environment)
- _RI price amortization calculation_; it's approximate because at the time ICE was created, there was no way to know exactly which Reserved Instance (RI) was covering a given instance hour execution)
- _Precise hourly based RI usage tracking_ (used by account it was bought on, borrowed by another account, lent to another account, unused, ...) which really helps understanding the rather complex nature of RIs
- _Normalization of "RI vs OD" EC2 instances prices_, when cost are tracked by Tags, in order to cope with the fact that RIs can jump from one instance to another on an hourly basis when instances are competing the same RIs (which leads to EC2 cost changing from one hour to the other)

Some of these features may look like too advanced but they are indeed usefull as soon as you do some serious cost reporting and cost analytics.

**Ice also has some features that are well ahead of most others cost management solutions**:
- **Cost by business metrics tracking** is probably the most important one. It lets you look at your cost in the most meaningfull way : prorated to the amount of actual business transaction your systems are processing (the hourly transaction volume has to be stored in a file on S3). This feature is very powerfull because it let's companies:
  - Track the cost effiency of your system rather than the cost itself
  - Detect system which are not properly sized or are not dynamically adjusting parts of their infrastructure (ie not using autoscaling for instance, or not using Lamdba)


**After all this about what ICE does, here are a few things that are missing from both Cost Reports and ICE:**

- Not a multi-user solution (not easy to share some costs to select people; some forks do enable that)
- Not easily usable by non technical people (kind of an expert tool); no predefined reports for instance
- No high-level dashboard that you can use to report to managers (too much detail)
- No explicit Cost reduction recommendations (RI purchase or RI resizing/relocation recommendations)
- No resource usage level analysis (to detect systems which are low on CPU, ...)
- No out-of-the-box solution for Tag normalization (there are so many typos in Tag names, not everybody is creating their infrastructure the 'IaC way')
- No out-of-the-box solution for Tagging untaggable resources
- No solutions to make correlations with outside events and their impact on costs (eg "DevOps events" like "system deployments", for instance and how much they impact costs).

**Shameless plug** : All these good things about ICE and also all these things lacking from ICE are the reason behind our choice to include ICE at the center of **Teevity (our SaaS service)** and **Teevity Incognito (the AWS Marketplace AMI version)** which is soon going to be available on the marketplace.

**Comment by jimkaushik** [comment]
Hi nfonrose,
I understand ICE can work with AWS detailed billing(hourly) reports ( <accountid>-aws-billing-detailed-line-items-<year>-<month>.csv.zip ). But this report has been deprecated by AWS and users have been asked to use the AWS Cost and Usage report.

Do you plan to update ICE work with the new report format : AWS Cost and Usage report.

**Comment by jimkaushik** [comment]
Hi @nfonrose ,
Appreciate the quick response. Looking forward to CUR (AWS Cost and Usage report) support by ICE OSS.
