### ISSUE TITLE
Data difference in AWS billing and Netflix ICE

### ISSUE THREAD

**Issue by durgadeviramadoss** [Teevity/ice#236]
Hi, 

Want to understand how Netflis is caluclating EC2 pricing. Because AWS billing data and what gives the value for ec2 differs. 

Say eg. my AWS billing for ec2 is 10k for this month
            Netflix data for ec2 is 16k for this month.

There is huge difference. Kindly let me how this can be handled.

**Comment by nfonrose** [comment]
Hello,

I guess you are using Reserved Instances. If this is the case, the
(16-10)==6k$ difference you are seeing is due to the difference between :

   - what's reported in the AWS bill (usage costs)
   - what's being reported by Ice (amortized value of instances).

ICE computes an amortized value for your EC2 instances. For each hour, the
amortized value equals the "Usage Price" (reported through the billing
files) + the Amortized RI cost (price of your RI spread accross its
duration).

This is why EC2 instances in ICE look more expensive than in the AWS bill.

Nicolas



PS : As there is no way, using the classical Billing Reports, to know which
RI exactly has been used to cover the execution of an instance hour, ICE
computes an amortization price which is based

   - Pricing information for RIs it gets from AWS
   - The default "RI type" parameter which tells it which type of RIs and
   which duration it should use for the computation

This is where your configure the default RI types to use for the
amortization computation

   # reservation period, possible values are oneyear, threeyear
    ice.reservationPeriod=threeyear
    # reservation utilization, possible values are LIGHT, HEAVY
    ice.reservationUtilization=HEAVY


--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity

**Comment by durgadeviramadoss** [comment]
Thanks Nicolas. 

Then if we are using RI, then ec2 cost will he high in Ice reports. If this is the case can you please specify any parameters in ice.properties file to get approx value in ice 

Regards,
Durga

**Comment by nfonrose** [comment]
On Wed, Jan 18, 2017 at 5:44 PM, durgadeviramadoss <notifications@github.com
> wrote:

> Thanks Nicolas.
>
> Then if we are using RI, then ec2 cost will he high in Ice reports. If
> this is the case can you please specify any parameters in ice.properties
> file to get approx value in ice
>
You have to adjust these parameters to match the type of RIs you use.
Assuming you use 1y AllUpfront RIs, the values below would probably be the
closest match.

   # reservation period, possible values are oneyear, threeyear
    ice.reservationPeriod=*oneyear*
    # reservation utilization, possible values are LIGHT, HEAVY
    ice.reservationUtilization=HEAVY

But, NetflixOSS ICE doesn't properly support the
AllUpfront/PartialUpfront/NoUpfront RI types and it mixes AllUpfront and
PartialUpfront prices. So it's only going to be an approximation.

Nicolas

Regards,
> Durga
>

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity

**Comment by durgadeviramadoss** [comment]
Thanks Nicolas for quick clarification

**Comment by durgadeviramadoss** [comment]
I have one more question as well in overall summary dashboard aggregated billing is less compared to AWS billing.

Say eg. My AWS consolidated Account billing is $49,297.90
            ICE consolidated account billing is $ 34,566.95.

Can you please explain why is this varying?

Regards,
Durga

**Comment by nfonrose** [comment]
The AWS bill contains all your purchases for the month (AWS MarketPlace, RIs, ...). 

The ICE reporting does not contain these expenses (expect for the amortized part of the RIs; cf previous email). 

Nicolas

**Comment by durgadeviramadoss** [comment]
Thanks Nicolas
