### ISSUE TITLE
Status of ice - Is it dead?

### ISSUE THREAD

**Issue by Esya** [Teevity/ice#240]
Hey all,

It seems that the netflix team has moved on and does not maintain it anymore. It currently sits with 28 pull requests and 80 open issues. Some pull requests seem to be adding great features, such as SAML Login, or even just some new AWS regions and instance types that are not included yet in ice.

It seems that there is no active fork either. 

There is no other open-source project similar to Ice, only commercial solutions, that are quite expensive. 

Would you consider giving rights to some active contributors to give a second life to this project? Or do you have another viable approach?

**Comment by andrewmcgilvray** [comment]
A guy from Teevity said they were going to update their fork a few month ago .. but it never happened. :-(

**Comment by nfonrose** [comment]
Hi Tristan and Andrew,

> A guy from Teevity said they were going to update their fork a few month
ago .. but it never happened. :-(

You are right. We've been very busy on other subjects ("RI optimization
algorithms" and "Resource Optimization Level Scoring") and have not updated
our fork with the latest AWS Regions.

*Can I ask what would be the most important things you would like to get
fixed first ?* I'm speaking to Tristan and Andrew, but also to the larger
Ice community. I'm pretty sure all of them are already fixed in our
internal (non public) fork so it's not necessarily are lot of work for us
to push them to our public fork (even though our internal fork and the
public Ice fork are very different now).

We are clearly interested in ensuring that the Ice project doesn't die
(even if we realize it's in a pretty bad shape right now) so your answer to
my the question above will be seriously taken into account.

Nicolas


PS : I just want to clarify that we are not operating as an OSS company,
meaning that we are not and will not publish all our source code as OSS.
It's possible that we don't intend to publish as OSS some of the things you
would like to see implemented in OSS Ice. But if that's the case :

   - We would simply say it
   - We won't block new pull requests by others that would implement these
   features (SAML integration being an example)




--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity

**Comment by TomGudman** [comment]
Hi Nicolas,

I think fixing the easy stuff first and creating some project activity would be welcome. 
Like: 
- Add new regions and zones
- Change the concept of HEAVY/LIGHT to upfront/partialupfront/noupfront (maybe not that easy;)
- Document the Reservation concept because the config is really vague (e.g: ice.reservationUtilization)

**Comment by amalakar** [comment]
@nfonrose curious has there been any progress or thought around making: https://github.com/Teevity/ice/ active? (like merging current open PRs etc). It would be nice to see ice becoming active again.

**Comment by JoshRosen** [comment]
ICE is a very useful tool but the project currently suffers from lack of maintenance. Users must maintain their own forks in order to fix basic issues, such as lack of support for new regions, resulting in lots of duplicated effort and frustration.

I'd like to propose the creation of a new GitHub organization to host a community-maintained fork of ICE. In order to prevent the new fork from dying again I would like to include users from multiple companies/organizations as committers / owners (the project could be adopted by a single organization and folks from other companies could be added as external GitHub repo collaborators, but that creates security / IT headaches).

Concretely, I would like to:

- Choose an appropriate GitHub organization name (such as ice-oss or ice-cost-tool).
- Fork Netflix/ice into the new organization.
- Set up a Gitter.im chat room to coordinate.
- Set up basic CI (using Travis or CircleCI).
- Create PRs to review and merge the obvious fixes from Netflix/ICE (such as the addition of new regions, fixing of typos, etc.).
- Encourage current ICE users to file new GitHub issues / PRs against the new repo.
- Maintain ICE via a lightweight review process which prioritizes merging of tested bugfixes. In the longer term we could consider merging major new features, but for now I'd like to focus on fixing the obvious issues with the current functionality. Once we've done that we can consider the process for longer-term feature development.
- If this fork is successful then eventually we may be able to get Netflix and GitHub to designate our fork as the canonical repository for the project (see https://webapps.stackexchange.com/questions/57911/how-does-one-change-the-canonical-repo-for-a-github-project).

One alternative would be to transfer the ownership of the ICE repo itself to the new organization (see https://help.github.com/articles/about-repository-transfers/), so existing forks would then point to our new organization's copy. This would make it easier to review the existing PRs and issues. I don't necessarily want to block on this, however, since getting someone from Netflix to sign off on it could be difficult.

Another alternative would be to get a larger OSS organization, such as Apache, to adopt the project, but that will be a much more complicated process.

If a few folks are willing to join me as initial maintainers and we can come up with a good organization name then I'd be happy to get the ball rolling on setting up the necessary project infrastructure.

(I also cross-posted this message to the iceusers Google Group at https://groups.google.com/forum/#!topic/iceusers/RzbcDCVPwU0)

**Comment by cpwatson** [comment]
Thanks for the comments @JoshRosen. My team here at Netflix owns ICE and in the past year developed a new solution (which we haven't open sourced) to better support our volume of data and analytic needs. I was in discussions with @nfonrose to perhaps have his fork at Teevity become the more "official" ICE-based project. 

Let me discuss internally and see what the best next steps forward might be in terms of the options you proposed above.

**Comment by zakcrawford** [comment]
Excited to hear that ICE is not dead at netflix, or at least a successor is under active development!

**Comment by shaneknapp** [comment]
super stoked to hear this as well!

**Comment by JoshRosen** [comment]
Hi @cpwatson, just checking in to see if you have any updates to share.

It would be great to collaborate with Teevity, but I'm not sure that actually hosting the community fork at Teevity is the best way for this to happen. Instead, I would propose to create a new GitHub organization and invite @nfonrose (and other folks from Teevity) as organization owners / admins. Having the ownership be shared among multiple organizations helps to ensure that the fork won't die due to individual maintainers or organizations moving on from the project.

**Comment by gyoza** [comment]
Can we call it Teevflix Ice so it sounds like beer?

**Comment by ghaber** [comment]
Hi all,

It seems Netflix has passes ownership of this repo to Teevity so I hope this mean the repo comes back to life again. I am ready to help.

Regards

**Comment by nfonrose** [comment]
It has actually come back to life already. We've pushed a few updates already (to make it compatible with all the latest regions), have setup an automated synchronizing of Ice releases with the Docker image built by jonbrouse.

The next step is to push a CloudFormation so that anybody can easily start Ice on their AWS accounts without having to fight with IAM rights and other issues.

And the next one is to include a basic test suite (focusing on the Processor logic, not the UI) so that people pushing PR can do so with the confidence that nothing has been broken inside the Ice core.

If you want to help, your more than welcome!

**Comment by ghaber** [comment]
Great news, I think it could be a good idea to create a to-do list so anybody can get a task to be done. A google group or similar with no spam would ne needed for communicating between us and get organized.

Regards

**Comment by PabloCastellano** [comment]
Since the project has been already transferred to Teevity, I think this issue is solved. [ICE has had more commits in the last 3 months than in the last year](https://github.com/Teevity/ice/graphs/contributors).

**Comment by csabaszilveszter** [comment]
How about now? Can't see any updates recently, also there's some spam on the google group. :)

Hoping to be able to use this (or any alternative) in a production env. Suggestions?

Thx in advance.
