### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by jonaustin** [Teevity/ice#289]
As it's been over a year and a half since the last commit; mainly I'm curious if there is support for the Cost and Usage Report; if not it might be helpful to put that in the Readme as it's now the standard.

Much thanks for the work you've done keeping this project going.

**Comment by andrewmcgilvray** [comment]
jimroth seems to be maintaining a pretty good fork : https://github.com/jimroth/ice/commits/master

**Comment by nfonrose** [comment]
Yes, @jimroth is doing a fantastic work. I haven't spoken with him yet, but I've been tracking his fork for a few months and he has not only added support for "Cost and Usage Report" but has also added a lot more.

This work would deserve to be a lot more visible so I hope he would be happy to submit a PullRequest. Having Jim contribute his work to upstream would by a great way to continue what Netflix has started years ago.

On the Teevity side, we are in a similar situation to the one Netflix was in a few years ago: our own internal fork has diverged pretty far away from upstream (because of all the things required to integrated with the rest of the Teevity SaaS solution) so it's super hard for us to make Pull Requests to upstream. The one part that we could probably pretty easily contribute upstream is the multi-cloud part (integration of GCP and AzureEA billing into Ice).

**Comment by jonaustin** [comment]
Great, thanks @andrewmcgilvray !

@nfonrose thanks for the update; since it might be a while until this repo can be updated, perhaps add a link to jimroth's fork in the readme.
